import Footer from "@/component/Footer.js";
import Header from "@/component/navigation/Header.js";
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono, Knewave, Titan_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const knewave = Knewave({
  variable: "--font-knewave",
  subsets: ["latin"],
  weight: "400",
});

const titan = Titan_One({
  variable: "--font-titan-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Matchify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="nord">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${knewave.variable} ${titan.variable} antialiased`}
      >
        <SessionProvider>
          <Header />
          <main className="">{children}</main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
